install.packages("reshape2")
install.packages("dplyr")
install.packages("bbmle")
install.packages("ggplot2")
install.packages("tidytext")
install.packages("data.table")
source("http://bioconductor.org/biocLite.R")
biocLite("phyloseq")
install.packages("topicmodels")

